const respostas = [
  "Certeza!",
  "Não tenho tanta certeza.",
  "É decididamente assim.", 
  "Não conte com isso.",
  "Sem dúvidas!",
  "Pergunte novamente mais tarde.", 
  "Sim, definitivamente",
  "Minha resposta é não.", 
  "Você pode contar com isso.", 
  "Melhor não te dizer agora.", 
  "A meu ver, sim.",
  "Minhas fontes dizem que não.",
  "Provavelmente.",
  "Não é possível prever agora.", 
  "Perspectiva boa.", 
  "As perspectivas não são tão boas.", 
  "Concentre-se e pergunte novamente.",
  "Sim.", 
  "Claro que não.", 
  "Claro que sim.", 
  "Os sinais apontam que sim.", 
  "Os sinais apontam que não.", 
  "Óbvio que sim.", 
  "Óbvio que não.", 
]